export const dataPlates = {
  data: {
    results: [
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: true,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 11,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 2,
        spoonacularScore: 92,
        healthScore: 90,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 168.12,
        id: 654959,
        title: "Pasta With Tuna",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl: "http://www.foodista.com/recipe/K6QWSKQM/pasta-with-tuna",
        image: "https://spoonacular.com/recipeImages/654959-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["lunch", "main course", "main dish", "dinner"],
        diets: ["pescatarian"],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Cook pasta in a large pot of boiling water until al dente.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                ],
                equipment: [
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
              },
              {
                number: 2,
                step: "Drain and return to warm pot. Put olive oil in saucepan and add onion.",
                ingredients: [
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 11282,
                    name: "onion",
                    localizedName: "onion",
                    image: "brown-onion.png",
                  },
                ],
                equipment: [
                  {
                    id: 404669,
                    name: "sauce pan",
                    localizedName: "sauce pan",
                    image: "sauce-pan.jpg",
                  },
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
              },
              {
                number: 3,
                step: "Saute until transparent. Stir in flour and cook for a few seconds and then whisk in milk. Stir constantly until this thickens.",
                ingredients: [
                  {
                    id: 20081,
                    name: "all purpose flour",
                    localizedName: "all purpose flour",
                    image: "flour.png",
                  },
                  {
                    id: 1077,
                    name: "milk",
                    localizedName: "milk",
                    image: "milk.png",
                  },
                ],
                equipment: [
                  {
                    id: 404661,
                    name: "whisk",
                    localizedName: "whisk",
                    image: "whisk.png",
                  },
                ],
              },
              {
                number: 4,
                step: "Add peas, tuna (shredded into chunks,) parsley, green onions, cheese and hot pepper sauce.",
                ingredients: [
                  {
                    id: 6168,
                    name: "hot sauce",
                    localizedName: "hot sauce",
                    image: "hot-sauce-or-tabasco.png",
                  },
                  {
                    id: 11291,
                    name: "green onions",
                    localizedName: "green onions",
                    image: "spring-onions.jpg",
                  },
                  {
                    id: 11297,
                    name: "parsley",
                    localizedName: "parsley",
                    image: "parsley.jpg",
                  },
                  {
                    id: 1041009,
                    name: "cheese",
                    localizedName: "cheese",
                    image: "cheddar-cheese.png",
                  },
                  {
                    id: 11304,
                    name: "peas",
                    localizedName: "peas",
                    image: "peas.jpg",
                  },
                  {
                    id: 10015121,
                    name: "tuna",
                    localizedName: "tuna",
                    image: "canned-tuna.png",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Pour over pasta and stir gently to mix.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 6,
                step: "Serve at once.",
                ingredients: [],
                equipment: [],
              },
            ],
          },
        ],
        spoonacularSourceUrl: "https://spoonacular.com/pasta-with-tuna-654959",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 24,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 1,
        spoonacularScore: 67,
        healthScore: 28,
        creditsText: "Pick Fresh Foods",
        license: "CC BY 3.0",
        sourceName: "Pick Fresh Foods",
        pricePerServing: 274.82,
        id: 511728,
        title: "Pasta Margherita",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl: "http://pickfreshfoods.com/pasta-margherita/",
        image: "https://spoonacular.com/recipeImages/511728-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["lunch", "main course", "main dish", "dinner"],
        diets: [],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Whisk oil, garlic, basil, salt together in large bowl.",
                ingredients: [
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 2044,
                    name: "basil",
                    localizedName: "basil",
                    image: "basil.jpg",
                  },
                  {
                    id: 2047,
                    name: "salt",
                    localizedName: "salt",
                    image: "salt.jpg",
                  },
                  {
                    id: 4582,
                    name: "cooking oil",
                    localizedName: "cooking oil",
                    image: "vegetable-oil.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404661,
                    name: "whisk",
                    localizedName: "whisk",
                    image: "whisk.png",
                  },
                  {
                    id: 404783,
                    name: "bowl",
                    localizedName: "bowl",
                    image: "bowl.jpg",
                  },
                ],
              },
              {
                number: 2,
                step: "Add tomatoes and mozzarella then gently toss to combine; set aside.Cook pasta according to package directions for al dente.",
                ingredients: [
                  {
                    id: 1026,
                    name: "mozzarella",
                    localizedName: "mozzarella",
                    image: "mozzarella.png",
                  },
                  {
                    id: 11529,
                    name: "tomato",
                    localizedName: "tomato",
                    image: "tomato.png",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 3,
                step: "Drain well.",
                ingredients: [],
                equipment: [],
              },
              {
                number: 4,
                step: "Add pasta to tomato mixture and gently toss to combine.",
                ingredients: [
                  {
                    id: 11529,
                    name: "tomato",
                    localizedName: "tomato",
                    image: "tomato.png",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Serve immediately.",
                ingredients: [],
                equipment: [],
              },
            ],
          },
        ],
        spoonacularSourceUrl: "https://spoonacular.com/pasta-margherita-511728",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 12,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 1,
        spoonacularScore: 69,
        healthScore: 28,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 616.45,
        id: 654812,
        title: "Pasta and Seafood",
        readyInMinutes: 45,
        servings: 2,
        sourceUrl: "http://www.foodista.com/recipe/8YWWDKPS/pasta-and-seafood",
        image: "https://spoonacular.com/recipeImages/654812-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["lunch", "main course", "main dish", "dinner"],
        diets: ["dairy free", "pescatarian"],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Bring water to a boil for pasta. Cook for 10 minutes or until al dente. In one saucepan heat half of the olive oil.",
                ingredients: [
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                ],
                equipment: [
                  {
                    id: 404669,
                    name: "sauce pan",
                    localizedName: "sauce pan",
                    image: "sauce-pan.jpg",
                  },
                ],
                length: {
                  number: 10,
                  unit: "minutes",
                },
              },
              {
                number: 2,
                step: "Add garlic and saute for a few seconds.",
                ingredients: [
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                ],
                equipment: [],
              },
              {
                number: 3,
                step: "Add tomatoes and cook for 5 minutes or until thickened; season with salt and pepper.In another skillet cook the shrimp in half the remaining olive oil.",
                ingredients: [
                  {
                    id: 1102047,
                    name: "salt and pepper",
                    localizedName: "salt and pepper",
                    image: "salt-and-pepper.jpg",
                  },
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 11529,
                    name: "tomato",
                    localizedName: "tomato",
                    image: "tomato.png",
                  },
                  {
                    id: 15270,
                    name: "shrimp",
                    localizedName: "shrimp",
                    image: "shrimp.png",
                  },
                ],
                equipment: [
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                ],
                length: {
                  number: 5,
                  unit: "minutes",
                },
              },
              {
                number: 4,
                step: "Remove from heat and toss in the parsley; season with salt and pepper.",
                ingredients: [
                  {
                    id: 1102047,
                    name: "salt and pepper",
                    localizedName: "salt and pepper",
                    image: "salt-and-pepper.jpg",
                  },
                  {
                    id: 11297,
                    name: "parsley",
                    localizedName: "parsley",
                    image: "parsley.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Drain pasta and transfer to a serving bowl; add shrimp and tomato mixtures and toss; do not serve with cheese.This recipe yields 2 servings.",
                ingredients: [
                  {
                    id: 1041009,
                    name: "cheese",
                    localizedName: "cheese",
                    image: "cheddar-cheese.png",
                  },
                  {
                    id: 15270,
                    name: "shrimp",
                    localizedName: "shrimp",
                    image: "shrimp.png",
                  },
                  {
                    id: 11529,
                    name: "tomato",
                    localizedName: "tomato",
                    image: "tomato.png",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404783,
                    name: "bowl",
                    localizedName: "bowl",
                    image: "bowl.jpg",
                  },
                ],
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-and-seafood-654812",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 10,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 1,
        spoonacularScore: 70,
        healthScore: 32,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 273.29,
        id: 654857,
        title: "Pasta On The Border",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl:
          "https://www.foodista.com/recipe/25DLQT8W/pasta-on-the-border",
        image: "https://spoonacular.com/recipeImages/654857-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
        diets: ["dairy free"],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Marinate strips of flank steak in a drizzle of EVOO, 2 smashed garlic cloves, juice of 1 lime (or lemon), 4 tbs. chopped cilantro and a dash of the seasonings for an hour or two.",
                ingredients: [
                  {
                    id: 10211215,
                    name: "whole garlic cloves",
                    localizedName: "whole garlic cloves",
                    image: "garlic.jpg",
                  },
                  {
                    id: 23657,
                    name: "flank steak",
                    localizedName: "flank steak",
                    image: "flank-steak.jpg",
                  },
                  {
                    id: 1042027,
                    name: "seasoning",
                    localizedName: "seasoning",
                    image: "seasoning.png",
                  },
                  {
                    id: 11165,
                    name: "cilantro",
                    localizedName: "cilantro",
                    image: "cilantro.png",
                  },
                  {
                    id: 1019016,
                    name: "juice",
                    localizedName: "juice",
                    image: "apple-juice.jpg",
                  },
                  {
                    id: 9150,
                    name: "lemon",
                    localizedName: "lemon",
                    image: "lemon.png",
                  },
                  {
                    id: 1034053,
                    name: "extra virgin olive oil",
                    localizedName: "extra virgin olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 9159,
                    name: "lime",
                    localizedName: "lime",
                    image: "lime.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 2,
                step: "If desired, brush jalapenos with a little oil and roast in 400F preheated oven for 30-40 minutes, turning over once halfway through.",
                ingredients: [
                  {
                    id: 11979,
                    name: "jalapeno pepper",
                    localizedName: "jalapeno pepper",
                    image: "jalapeno-pepper.png",
                  },
                  {
                    id: 4582,
                    name: "cooking oil",
                    localizedName: "cooking oil",
                    image: "vegetable-oil.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404784,
                    name: "oven",
                    localizedName: "oven",
                    image: "oven.jpg",
                    temperature: {
                      number: 400,
                      unit: "Fahrenheit",
                    },
                  },
                ],
                length: {
                  number: 40,
                  unit: "minutes",
                },
              },
              {
                number: 3,
                step: "In a sauce pan, heat the enchilada sauce until boiling then add the beans. Stir for another couple of minutes and turn off heat.",
                ingredients: [
                  {
                    id: 6599,
                    name: "enchilada sauce",
                    localizedName: "enchilada sauce",
                    image: "harissa.jpg",
                  },
                  {
                    id: 0,
                    name: "beans",
                    localizedName: "beans",
                    image: "kidney-beans.jpg",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                ],
                equipment: [
                  {
                    id: 404669,
                    name: "sauce pan",
                    localizedName: "sauce pan",
                    image: "sauce-pan.jpg",
                  },
                ],
              },
              {
                number: 4,
                step: "In a medium-heated skillet, add a little EVOO and saut the beef strips along with the minced garlic and the julienned onion and bell pepper(s).",
                ingredients: [
                  {
                    id: 0,
                    name: "minced garlic",
                    localizedName: "minced garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 10211821,
                    name: "bell pepper",
                    localizedName: "bell pepper",
                    image: "bell-pepper-orange.png",
                  },
                  {
                    id: 11282,
                    name: "onion",
                    localizedName: "onion",
                    image: "brown-onion.png",
                  },
                  {
                    id: 23572,
                    name: "beef",
                    localizedName: "beef",
                    image: "beef-cubes-raw.png",
                  },
                  {
                    id: 1034053,
                    name: "extra virgin olive oil",
                    localizedName: "extra virgin olive oil",
                    image: "olive-oil.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                ],
              },
              {
                number: 5,
                step: "Stack the tortillas on top of each other and roll as tight as you can without tearing it. Now, using a very sharp knife, thinly slice the roll from one end to the other creating fettuccine-like strands. Loosen strands and coat with EVOO and a dash of the seasonings.",
                ingredients: [
                  {
                    id: 10020409,
                    name: "fettuccine",
                    localizedName: "fettuccine",
                    image: "egg-noodles.jpg",
                  },
                  {
                    id: 1042027,
                    name: "seasoning",
                    localizedName: "seasoning",
                    image: "seasoning.png",
                  },
                  {
                    id: 18364,
                    name: "tortilla",
                    localizedName: "tortilla",
                    image: "flour-tortilla.jpg",
                  },
                  {
                    id: 1034053,
                    name: "extra virgin olive oil",
                    localizedName: "extra virgin olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 0,
                    name: "roll",
                    localizedName: "roll",
                    image: "dinner-yeast-rolls.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404745,
                    name: "knife",
                    localizedName: "knife",
                    image: "chefs-knife.jpg",
                  },
                ],
              },
              {
                number: 6,
                step: "Spread tortilla strands out on individual serving platters, top each with enchilada/bean mixture, salsa and beef/veggie mixture.",
                ingredients: [
                  {
                    id: 18364,
                    name: "tortilla",
                    localizedName: "tortilla",
                    image: "flour-tortilla.jpg",
                  },
                  {
                    id: 0,
                    name: "spread",
                    localizedName: "spread",
                    image: "",
                  },
                  {
                    id: 6164,
                    name: "salsa",
                    localizedName: "salsa",
                    image: "salsa.png",
                  },
                  {
                    id: 23572,
                    name: "beef",
                    localizedName: "beef",
                    image: "beef-cubes-raw.png",
                  },
                ],
                equipment: [],
              },
              {
                number: 7,
                step: "Garnish with remaining chopped cilantro, a lime (or lemon) wedge and a roasted jalapeno pepper.",
                ingredients: [
                  {
                    id: 11979,
                    name: "jalapeno pepper",
                    localizedName: "jalapeno pepper",
                    image: "jalapeno-pepper.png",
                  },
                  {
                    id: 11165,
                    name: "cilantro",
                    localizedName: "cilantro",
                    image: "cilantro.png",
                  },
                  {
                    id: 9150,
                    name: "lemon",
                    localizedName: "lemon",
                    image: "lemon.png",
                  },
                  {
                    id: 9159,
                    name: "lime",
                    localizedName: "lime",
                    image: "lime.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 8,
                step: "Another optional item you can add is shredded cheese. Before garnishing, top with shredded cheese and pop the plate in the microwave for a minute or until cheese has fully melted.",
                ingredients: [
                  {
                    id: 1011026,
                    name: "shredded cheese",
                    localizedName: "shredded cheese",
                    image: "cheddar-cheese.png",
                  },
                  {
                    id: 1041009,
                    name: "cheese",
                    localizedName: "cheese",
                    image: "cheddar-cheese.png",
                  },
                  {
                    id: 0,
                    name: "pop",
                    localizedName: "soft drink",
                    image: "",
                  },
                ],
                equipment: [
                  {
                    id: 404762,
                    name: "microwave",
                    localizedName: "microwave",
                    image: "microwave.jpg",
                  },
                ],
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-on-the-border-654857",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 3,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 1,
        spoonacularScore: 73,
        healthScore: 27,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 67.61,
        id: 654883,
        title: "Pasta Vegetable Soup",
        readyInMinutes: 45,
        servings: 10,
        sourceUrl:
          "http://www.foodista.com/recipe/FR8FKR4F/pasta-vegetable-soup",
        image: "https://spoonacular.com/recipeImages/654883-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["soup"],
        diets: [],
        occasions: ["fall", "winter"],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "In a large sauce pan, combine 4 cups water, onion, carrot, celery, brown sugar, basil, marjoram, oregano, thyme, pepper, garlic, chicken broth, tomatoes, beans, and tomato paste then bring to a boil. Cover, reduce heat, and simmer 45 minutes.",
                ingredients: [
                  {
                    id: 6194,
                    name: "chicken broth",
                    localizedName: "chicken broth",
                    image: "chicken-broth.png",
                  },
                  {
                    id: 11887,
                    name: "tomato paste",
                    localizedName: "tomato paste",
                    image: "tomato-paste.jpg",
                  },
                  {
                    id: 19334,
                    name: "brown sugar",
                    localizedName: "brown sugar",
                    image: "dark-brown-sugar.png",
                  },
                  {
                    id: 2023,
                    name: "marjoram",
                    localizedName: "marjoram",
                    image: "marjoram.jpg",
                  },
                  {
                    id: 11529,
                    name: "tomato",
                    localizedName: "tomato",
                    image: "tomato.png",
                  },
                  {
                    id: 2027,
                    name: "oregano",
                    localizedName: "oregano",
                    image: "oregano.jpg",
                  },
                  {
                    id: 11124,
                    name: "carrot",
                    localizedName: "carrot",
                    image: "sliced-carrot.png",
                  },
                  {
                    id: 11143,
                    name: "celery",
                    localizedName: "celery",
                    image: "celery.jpg",
                  },
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 1002030,
                    name: "pepper",
                    localizedName: "pepper",
                    image: "pepper.jpg",
                  },
                  {
                    id: 2044,
                    name: "basil",
                    localizedName: "basil",
                    image: "basil.jpg",
                  },
                  {
                    id: 0,
                    name: "beans",
                    localizedName: "beans",
                    image: "kidney-beans.jpg",
                  },
                  {
                    id: 11282,
                    name: "onion",
                    localizedName: "onion",
                    image: "brown-onion.png",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                  {
                    id: 2049,
                    name: "thyme",
                    localizedName: "thyme",
                    image: "thyme.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                ],
                equipment: [
                  {
                    id: 404669,
                    name: "sauce pan",
                    localizedName: "sauce pan",
                    image: "sauce-pan.jpg",
                  },
                ],
                length: {
                  number: 45,
                  unit: "minutes",
                },
              },
              {
                number: 2,
                step: "Add remaining 2 cups water; bring to a boil. Stir in macaroni, and cook an additional 8 minutes. Ladle into soup bowls; top with Parmesan cheese.",
                ingredients: [
                  {
                    id: 1033,
                    name: "parmesan",
                    localizedName: "parmesan",
                    image: "parmesan.jpg",
                  },
                  {
                    id: 20499,
                    name: "macaroni",
                    localizedName: "macaroni",
                    image: "macaroni.png",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                  {
                    id: 0,
                    name: "soup",
                    localizedName: "soup",
                    image: "",
                  },
                ],
                equipment: [
                  {
                    id: 404783,
                    name: "bowl",
                    localizedName: "bowl",
                    image: "bowl.jpg",
                  },
                  {
                    id: 404630,
                    name: "ladle",
                    localizedName: "ladle",
                    image: "ladle.jpg",
                  },
                ],
                length: {
                  number: 8,
                  unit: "minutes",
                },
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-vegetable-soup-654883",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 28,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 1,
        spoonacularScore: 73,
        healthScore: 30,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 245.44,
        id: 654928,
        title: "Pasta With Italian Sausage",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl:
          "http://www.foodista.com/recipe/G8JXNCD8/pasta-with-italian-sausage",
        image: "https://spoonacular.com/recipeImages/654928-312x231.jpg",
        imageType: "jpg",
        cuisines: ["Mediterranean", "Italian", "European"],
        dishTypes: ["lunch", "main course", "main dish", "dinner"],
        diets: [],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Crumble sausage into a large skillet. Cook over medium heat, stirring often, until meat is well browned.",
                ingredients: [
                  {
                    id: 1017063,
                    name: "sausage",
                    localizedName: "sausage",
                    image: "raw-pork-sausage.png",
                  },
                  {
                    id: 1065062,
                    name: "meat",
                    localizedName: "meat",
                    image: "whole-chicken.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                ],
              },
              {
                number: 2,
                step: "Drain and set aside. In same skillet, cook onion, pepper, garlic, basil and fennel in 1 tb olive oil over medium heat, stirring often to scrape up browned bits from the bottom of pan. Cook until onion is translucent, about 5 minutes.",
                ingredients: [
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 11957,
                    name: "fennel",
                    localizedName: "fennel",
                    image: "fennel.png",
                  },
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 1002030,
                    name: "pepper",
                    localizedName: "pepper",
                    image: "pepper.jpg",
                  },
                  {
                    id: 2044,
                    name: "basil",
                    localizedName: "basil",
                    image: "basil.jpg",
                  },
                  {
                    id: 11282,
                    name: "onion",
                    localizedName: "onion",
                    image: "brown-onion.png",
                  },
                ],
                equipment: [
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                ],
                length: {
                  number: 5,
                  unit: "minutes",
                },
              },
              {
                number: 3,
                step: "Add sausage, pasta sauce, and wine. Bring to a boil. Reduce heat and simmer 5 minutes. While sauce is cooking, in a large pot of boiling water cook pasta until al dente.",
                ingredients: [
                  {
                    id: 10011549,
                    name: "pasta sauce",
                    localizedName: "pasta sauce",
                    image: "tomato-sauce-or-pasta-sauce.jpg",
                  },
                  {
                    id: 1017063,
                    name: "sausage",
                    localizedName: "sausage",
                    image: "raw-pork-sausage.png",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                  {
                    id: 14084,
                    name: "wine",
                    localizedName: "wine",
                    image: "red-wine.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
                length: {
                  number: 5,
                  unit: "minutes",
                },
              },
              {
                number: 4,
                step: "Drain well.On a large warm serving platter, combine parsley and 1 tb olive oil & fresh basil.",
                ingredients: [
                  {
                    id: 2044,
                    name: "fresh basil",
                    localizedName: "fresh basil",
                    image: "fresh-basil.jpg",
                  },
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 11297,
                    name: "parsley",
                    localizedName: "parsley",
                    image: "parsley.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Add pasta and toss to mix.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 6,
                step: "Pour sauce over pasta.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                ],
                equipment: [],
              },
              {
                number: 7,
                step: "Sprinkle with Parmesean cheese.",
                ingredients: [
                  {
                    id: 1041009,
                    name: "cheese",
                    localizedName: "cheese",
                    image: "cheddar-cheese.png",
                  },
                ],
                equipment: [],
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-with-italian-sausage-654928",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 14,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 1,
        spoonacularScore: 24,
        healthScore: 2,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 67.99,
        id: 654926,
        title: "Pasta With Gorgonzola Sauce",
        readyInMinutes: 45,
        servings: 8,
        sourceUrl:
          "http://www.foodista.com/recipe/SJLPWK55/pasta-with-gorgonzola-sauce",
        image: "https://spoonacular.com/recipeImages/654926-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["side dish"],
        diets: [],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "In an enamel saucepan, melt the butter over low heat, add the Gorgonzola cheese, Half and Half, and salt. Mash the Gorgonzola with a wooden spoon and stir to mix over a low flame. Cook about 1 minute until sauce becomes thick and creamy. In the meantime, cook the pasta according to the package directions and drain. Just before fettuccini is done, stir the whipping cream into the cheese sauce over a low flame.",
                ingredients: [
                  {
                    id: 1011004,
                    name: "gorgonzola",
                    localizedName: "gorgonzola",
                    image: "gorgonzola.jpg",
                  },
                  {
                    id: 1001053,
                    name: "whipping cream",
                    localizedName: "whipping cream",
                    image: "fluid-cream.jpg",
                  },
                  {
                    id: 1049,
                    name: "half and half",
                    localizedName: "half and half",
                    image: "fluid-cream.jpg",
                  },
                  {
                    id: 0,
                    name: "cheese sauce",
                    localizedName: "cheese sauce",
                    image: "",
                  },
                  {
                    id: 10020409,
                    name: "fettuccine",
                    localizedName: "fettuccine",
                    image: "egg-noodles.jpg",
                  },
                  {
                    id: 1001,
                    name: "butter",
                    localizedName: "butter",
                    image: "butter-sliced.jpg",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                  {
                    id: 2047,
                    name: "salt",
                    localizedName: "salt",
                    image: "salt.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404732,
                    name: "wooden spoon",
                    localizedName: "wooden spoon",
                    image: "wooden-spoon.jpg",
                  },
                  {
                    id: 404669,
                    name: "sauce pan",
                    localizedName: "sauce pan",
                    image: "sauce-pan.jpg",
                  },
                ],
                length: {
                  number: 1,
                  unit: "minutes",
                },
              },
              {
                number: 2,
                step: "Place the pasta on a warm platter and pour sauce over. Toss until coat",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                ],
                equipment: [],
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-with-gorgonzola-sauce-654926",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 13,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 3,
        spoonacularScore: 67,
        healthScore: 21,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 160.13,
        id: 654944,
        title: "Pasta With Salmon Cream Sauce",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl:
          "http://www.foodista.com/recipe/WRF73JT3/pasta-with-salmon-cream-sauce",
        image: "https://spoonacular.com/recipeImages/654944-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["lunch", "main course", "main dish", "dinner"],
        diets: ["pescatarian"],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Calories per serving: 300 In large pot of boiling water, cook pasta al dente (tender but firm) about 10 12 minutes.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                ],
                equipment: [
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
                length: {
                  number: 12,
                  unit: "minutes",
                },
              },
              {
                number: 2,
                step: "Drain and return to pot. In saucepan, melt butter over medium heat add onion and cook until tender.Stir in flour and cook for a few seconds.",
                ingredients: [
                  {
                    id: 1001,
                    name: "butter",
                    localizedName: "butter",
                    image: "butter-sliced.jpg",
                  },
                  {
                    id: 20081,
                    name: "all purpose flour",
                    localizedName: "all purpose flour",
                    image: "flour.png",
                  },
                  {
                    id: 11282,
                    name: "onion",
                    localizedName: "onion",
                    image: "brown-onion.png",
                  },
                ],
                equipment: [
                  {
                    id: 404669,
                    name: "sauce pan",
                    localizedName: "sauce pan",
                    image: "sauce-pan.jpg",
                  },
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
              },
              {
                number: 3,
                step: "Whisk in milk and bring to sa simmer, stirring constantly.",
                ingredients: [
                  {
                    id: 1077,
                    name: "milk",
                    localizedName: "milk",
                    image: "milk.png",
                  },
                ],
                equipment: [
                  {
                    id: 404661,
                    name: "whisk",
                    localizedName: "whisk",
                    image: "whisk.png",
                  },
                ],
              },
              {
                number: 4,
                step: "Add peas, salmon brokin into chunks and salmon juices, parsley, cheese, pepper.",
                ingredients: [
                  {
                    id: 11297,
                    name: "parsley",
                    localizedName: "parsley",
                    image: "parsley.jpg",
                  },
                  {
                    id: 1041009,
                    name: "cheese",
                    localizedName: "cheese",
                    image: "cheddar-cheese.png",
                  },
                  {
                    id: 1002030,
                    name: "pepper",
                    localizedName: "pepper",
                    image: "pepper.jpg",
                  },
                  {
                    id: 15076,
                    name: "salmon",
                    localizedName: "salmon",
                    image: "salmon.png",
                  },
                  {
                    id: 11304,
                    name: "peas",
                    localizedName: "peas",
                    image: "peas.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Pour mixture over pasta and stir gently to mix.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 6,
                step: "Serve Immediately. Microwave method: Cook pasta as above in glass bowl or 4 cup measure. Microwave butter and onion at Medium-High for 1 minute or until onion is tender. Stir in flour to form smooth paste. Gradually whisk in milk.",
                ingredients: [
                  {
                    id: 1001,
                    name: "butter",
                    localizedName: "butter",
                    image: "butter-sliced.jpg",
                  },
                  {
                    id: 20081,
                    name: "all purpose flour",
                    localizedName: "all purpose flour",
                    image: "flour.png",
                  },
                  {
                    id: 11282,
                    name: "onion",
                    localizedName: "onion",
                    image: "brown-onion.png",
                  },
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 1077,
                    name: "milk",
                    localizedName: "milk",
                    image: "milk.png",
                  },
                ],
                equipment: [
                  {
                    id: 404762,
                    name: "microwave",
                    localizedName: "microwave",
                    image: "microwave.jpg",
                  },
                  {
                    id: 404661,
                    name: "whisk",
                    localizedName: "whisk",
                    image: "whisk.png",
                  },
                  {
                    id: 404783,
                    name: "bowl",
                    localizedName: "bowl",
                    image: "bowl.jpg",
                  },
                ],
                length: {
                  number: 1,
                  unit: "minutes",
                },
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-with-salmon-cream-sauce-654944",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: true,
        veryHealthy: true,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 16,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 2,
        spoonacularScore: 94,
        healthScore: 100,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 142.74,
        id: 654905,
        title: "Pasta With Chickpeas and Kale",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl:
          "http://www.foodista.com/recipe/4BTWKPRC/pasta-with-chickpeas-and-kale",
        image: "https://spoonacular.com/recipeImages/654905-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["lunch", "main course", "main dish", "dinner"],
        diets: ["dairy free"],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Set a large pot of water to boil, and add salt.",
                ingredients: [
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                  {
                    id: 2047,
                    name: "salt",
                    localizedName: "salt",
                    image: "salt.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
              },
              {
                number: 2,
                step: "Cut the kale stems into 2-3 inch pieces; chop the leaves coarsely and set aside. Boil the stems until they are nearly tender; then, add the greens. Cook until kale is quite tender but stillbright green. Scoop it out with a slotted spoon, place in a bowl of ice water, and keep pot boiling. When the kale cools, squeeze out excess water, gather it into a mass and chop rather finely. Meanwhile, place olive oil in a large skillet over veWarm the garlic mixture over medium heat, and add the cooked pasta, the chickpeas and the chopped kale.Toss well, taste for seasoning, garnish with parsley and serve immediately.",
                ingredients: [
                  {
                    id: 20421,
                    name: "cooked pasta",
                    localizedName: "cooked pasta",
                    image: "fusilli.jpg",
                  },
                  {
                    id: 16057,
                    name: "chickpeas",
                    localizedName: "chickpeas",
                    image: "chickpeas.png",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 1042027,
                    name: "seasoning",
                    localizedName: "seasoning",
                    image: "seasoning.png",
                  },
                  {
                    id: 11297,
                    name: "parsley",
                    localizedName: "parsley",
                    image: "parsley.jpg",
                  },
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 21052,
                    name: "greens",
                    localizedName: "greens",
                    image: "mixed-greens-or-mesclun.jpg",
                  },
                  {
                    id: 11233,
                    name: "kale",
                    localizedName: "kale",
                    image: "kale.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404636,
                    name: "slotted spoon",
                    localizedName: "slotted spoon",
                    image: "slotted-spoon.jpg",
                  },
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                  {
                    id: 404783,
                    name: "bowl",
                    localizedName: "bowl",
                    image: "bowl.jpg",
                  },
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image: "stock-pot.jpg",
                  },
                ],
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-with-chickpeas-and-kale-654905",
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 8,
        gaps: "no",
        lowFodmap: false,
        aggregateLikes: 3,
        spoonacularScore: 56,
        healthScore: 15,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 145.96,
        id: 654901,
        title: "Pasta With Chicken and Broccoli",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl:
          "https://www.foodista.com/recipe/Y5X6DRHT/pasta-with-chicken-and-broccoli",
        image: "https://spoonacular.com/recipeImages/654901-312x231.jpg",
        imageType: "jpg",
        cuisines: [],
        dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
        diets: [],
        occasions: [],
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "In a large skillet, heat oil over medium heat.",
                ingredients: [
                  {
                    id: 4582,
                    name: "cooking oil",
                    localizedName: "cooking oil",
                    image: "vegetable-oil.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                ],
              },
              {
                number: 2,
                step: "Sautee garlic for about one minute, stirring constantly. DO NOT BURN.",
                ingredients: [
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                ],
                equipment: [],
                length: {
                  number: 1,
                  unit: "minutes",
                },
              },
              {
                number: 3,
                step: "Add the chicken and cook until well done.",
                ingredients: [
                  {
                    id: 5006,
                    name: "whole chicken",
                    localizedName: "whole chicken",
                    image: "whole-chicken.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 4,
                step: "Add the broccoli and cook until crisp but tender.",
                ingredients: [
                  {
                    id: 11090,
                    name: "broccoli",
                    localizedName: "broccoli",
                    image: "broccoli.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Add basil; red pepper; salt and pepper to taste; wine and chicken broth. cook for about 5 minutes.",
                ingredients: [
                  {
                    id: 1102047,
                    name: "salt and pepper",
                    localizedName: "salt and pepper",
                    image: "salt-and-pepper.jpg",
                  },
                  {
                    id: 6194,
                    name: "chicken broth",
                    localizedName: "chicken broth",
                    image: "chicken-broth.png",
                  },
                  {
                    id: 11821,
                    name: "red pepper",
                    localizedName: "red pepper",
                    image: "red-pepper.jpg",
                  },
                  {
                    id: 2044,
                    name: "basil",
                    localizedName: "basil",
                    image: "basil.jpg",
                  },
                  {
                    id: 14084,
                    name: "wine",
                    localizedName: "wine",
                    image: "red-wine.jpg",
                  },
                ],
                equipment: [],
                length: {
                  number: 5,
                  unit: "minutes",
                },
              },
              {
                number: 6,
                step: "Add the cooked and drained pasta to the skillet and toss to combine.",
                ingredients: [
                  {
                    id: 20420,
                    name: "pasta",
                    localizedName: "pasta",
                    image: "fusilli.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404645,
                    name: "frying pan",
                    localizedName: "frying pan",
                    image: "pan.png",
                  },
                ],
              },
              {
                number: 7,
                step: "Heat for 1 to 2 minutes",
                ingredients: [],
                equipment: [],
              },
              {
                number: 8,
                step: "Serve.",
                ingredients: [],
                equipment: [],
              },
              {
                number: 9,
                step: "Top with grated Parmesan cheese if desired.",
                ingredients: [
                  {
                    id: 1032,
                    name: "grated parmesan cheese",
                    localizedName: "grated parmesan cheese",
                    image: "parmesan.jpg",
                  },
                ],
                equipment: [],
              },
            ],
          },
        ],
        spoonacularSourceUrl:
          "https://spoonacular.com/pasta-with-chicken-and-broccoli-654901",
      },
    ],
    offset: 0,
    number: 10,
    totalResults: 224,
  },
  status: 200,
  statusText: "",
  headers: {
    "content-type": "application/json",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    method: "get",
    url: "https://api.spoonacular.com/recipes/complexSearch?apiKey=5f0c5f3f4d504316811ad47a69ddf8b6&query=pasta&addRecipeInformation=true",
  },
  request: {},
};
